<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VVVV" name="FuncTest" tests="4" failures="1" timestamp="9 Mar 2016 21:09:46 GMT" time="37.277" errors="0">
  <testcase name="clickOnLoginTest" time="3.817" classname="com.test.HomePageTest"/>
  <testcase name="countSocialIconsTest" time="0.07" classname="com.test.HomePageTest"/>
  <testcase name="invalidLoginTest" time="1.975" classname="com.test.LoginPageTest"/>
  <testcase name="invalidLoginTest" time="0.595" classname="com.test.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Something went wrong...Please try again.&amp;gt; but was:&amp;lt;&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Something went wrong...Please try again.> but was:<>
	at com.test.LoginPageTest.invalidLoginTest(LoginPageTest.java:37)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
</testsuite> <!-- FuncTest -->
